default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "GB Blog"

development:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
