common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *common
  database: gb-blog_development

test:
  <<: *common
  database: gb-blog_test

production:
  <<: *common
  database: gb-blog
